# Whether players keep fall damage after performing a double jump.
preserveFallDamage: true

# Prevents conflicts with flying abilities.
avoidFlyConflicts: true

# Use server-side ground detection instead of trusting client packets.
# Prevents exploits but may cause slight delays on high-latency connections.
hardenedGroundCheck: false

# When double jumping should be allowed:
#   ALL        - Available to everyone.
#   PERMISSION - Players need a specific permission.
#   ITEM       - Granted via custom item abilities powered by our API.
activationMethod: "ALL"

# Technical double jump configuration.
# API integrations may override these settings.
jump-settings:
  # Delay between consecutive double jumps (in server ticks; 20 ticks = 1 second).
  # To disable double jump cooldowns, set this value to 0 or less.
  cooldown-ticks: 0

  # The amount of hunger points that should be deducted per double jump.
  # 1 point = half a drumstick; set to 0 to disable hunger drain.
  hunger-drain: 1

  # Factor applied to the normalised look vector to compute horizontal velocity.
  # In simpler terms, increasing this value makes you travel farther horizontally.
  horizontal-force-multiplier: 0.5

  # The upward velocity applied when performing a double jumping.
  # Measured in blocks per tick; increase for a stronger vertical boost.
  vertical-velocity: 0.42

  # Double jump effects configuration.
  effects:
    sound:
      # Whether sound effects should be played whenever you double jump.
      enabled: true

      # The vanilla Minecraft sound to play whenever double jumping.
      source: "entity.ender_dragon.flap"

      # The volume level for the sound effect (0.0 to 1.0).
      volume: 0.5

      # The pitch modifier for the sound effect (0.0 to 2.0).
      pitch: 1.32
