name: SDJ
main: me.rarehyperion.simpledoublejump.SDJ
authors: [RareHyperIon]
version: '0.1.0'
api-version: '1.13'
load: STARTUP

commands:
  sdj:
    description: "Reload the plugins configuration."
    permission: sdj.admin
    usage: /sdj reload

permissions:
  sdj.admin:
    description: "Allows for reloading the plugins configuration."
    default: op
  sdj.use:
    description: "Allows you to double jump."
    default: op